const LANGUAGES = {
  "af":     { endonym: "Afrikaans",           english: "Afrikaans" },
  "sq":     { endonym: "Shqip",               english: "Albanian" },
  "am":     { endonym: "አማርኛ",                english: "Amharic" },
  "ar":     { endonym: "العربية",             english: "Arabic" },
  "hy":     { endonym: "Հայերեն",             english: "Armenian" },
  "as":     { endonym: "অসমীয়া",              english: "Assamese" },
  "ay":     { endonym: "Aymar aru",           english: "Aymara" },
  "az":     { endonym: "Azərbaycan",          english: "Azerbaijani" },
  "bn":     { endonym: "বাংলা",                english: "Bangla" },
  "ba":     { endonym: "Башҡорт",             english: "Bashkir" },
  "eu":     { endonym: "Euskara",             english: "Basque" },
  "be":     { endonym: "Беларуская",          english: "Belarusian" },
  "bho":    { endonym: "भोजपुरी",              english: "Bhojpuri" },
  "bs":     { endonym: "Bosanski",            english: "Bosnian" },
  "bg":     { endonym: "Български",           english: "Bulgarian" },
  "my":     { endonym: "မြန်မာ",               english: "Burmese" },
  "ca":     { endonym: "Català",              english: "Catalan" },
  "ceb":    { endonym: "Cebuano",             english: "Cebuano" },
  "zh-CN":  { endonym: "简体中文",             english: "Chinese (Simplified)" },
  "zh-TW":  { endonym: "繁體中文",             english: "Chinese (Traditional)" },
  "co":     { endonym: "Corsu",               english: "Corsican" },
  "hr":     { endonym: "Hrvatski",            english: "Croatian" },
  "cs":     { endonym: "Čeština",             english: "Czech" },
  "da":     { endonym: "Dansk",               english: "Danish" },
  "dv":     { endonym: "ދިވެހި",               english: "Dhivehi" },
  "nl":     { endonym: "Nederlands",          english: "Dutch" },
  "dz":     { endonym: "རྫོང་ཁ",                english: "Dzongkha" },
  "en":     { endonym: "English",             english: "English" },
  "eo":     { endonym: "Esperanto",           english: "Esperanto" },
  "et":     { endonym: "Eesti",               english: "Estonian" },
  "ee":     { endonym: "Eʋegbe",              english: "Ewe" },
  "fo":     { endonym: "Føroyskt",            english: "Faroese" },
  "fj":     { endonym: "Vosa Vakaviti",       english: "Fijian" },
  "fil":    { endonym: "Filipino",            english: "Filipino" },
  "fi":     { endonym: "Suomi",               english: "Finnish" },
  "fr":     { endonym: "Français",            english: "French" },
  "gaa":    { endonym: "Gã",                  english: "Ga" },
  "gl":     { endonym: "Galego",              english: "Galician" },
  "lg":     { endonym: "Luganda",             english: "Ganda" },
  "ka":     { endonym: "ქართული",             english: "Georgian" },
  "de":     { endonym: "Deutsch",             english: "German" },
  "el":     { endonym: "Ελληνικά",            english: "Greek" },
  "gn":     { endonym: "Avañe'ẽ",             english: "Guarani" },
  "gu":     { endonym: "ગુજરાતી",              english: "Gujarati" },
  "ht":     { endonym: "Kreyòl ayisyen",      english: "Haitian Creole" },
  "ha":     { endonym: "Hausa",               english: "Hausa" },
  "haw":    { endonym: "ʻŌlelo Hawaiʻi",      english: "Hawaiian" },
  "iw":     { endonym: "עברית",               english: "Hebrew" },
  "hi":     { endonym: "हिन्दी",                english: "Hindi" },
  "hmn":    { endonym: "Hmoob",               english: "Hmong" },
  "hu":     { endonym: "Magyar",              english: "Hungarian" },
  "is":     { endonym: "Íslenska",            english: "Icelandic" },
  "ig":     { endonym: "Igbo",                english: "Igbo" },
  "id":     { endonym: "Bahasa Indonesia",    english: "Indonesian" },
  "ga":     { endonym: "Gaeilge",             english: "Irish" },
  "it":     { endonym: "Italiano",            english: "Italian" },
  "ja":     { endonym: "日本語",               english: "Japanese" },
  "jv":     { endonym: "Basa Jawa",           english: "Javanese" },
  "kn":     { endonym: "ಕನ್ನಡ",                english: "Kannada" },
  "kk":     { endonym: "Қазақ",               english: "Kazakh" },
  "km":     { endonym: "ខ្មែរ",                 english: "Khmer" },
  "rw":     { endonym: "Kinyarwanda",         english: "Kinyarwanda" },
  "kri":    { endonym: "Krio",                english: "Krio" },
  "ko":     { endonym: "한국어",               english: "Korean" },
  "ku":     { endonym: "Kurdî",               english: "Kurdish" },
  "ky":     { endonym: "Кыргызча",            english: "Kyrgyz" },
  "lo":     { endonym: "ລາວ",                 english: "Lao" },
  "la":     { endonym: "Latina",              english: "Latin" },
  "lv":     { endonym: "Latviešu",            english: "Latvian" },
  "ln":     { endonym: "Lingála",             english: "Lingala" },
  "lt":     { endonym: "Lietuvių",            english: "Lithuanian" },
  "lb":     { endonym: "Lëtzebuergesch",      english: "Luxembourgish" },
  "mk":     { endonym: "Македонски",          english: "Macedonian" },
  "mai":    { endonym: "मैथिली",               english: "Maithili" },
  "mg":     { endonym: "Malagasy",            english: "Malagasy" },
  "ms":     { endonym: "Bahasa Melayu",       english: "Malay" },
  "ml":     { endonym: "മലയാളം",              english: "Malayalam" },
  "mt":     { endonym: "Malti",               english: "Maltese" },
  "mi":     { endonym: "Māori",               english: "Māori" },
  "mr":     { endonym: "मराठी",                english: "Marathi" },
  "mn":     { endonym: "Монгол",              english: "Mongolian" },
  "ne":     { endonym: "नेपाली",               english: "Nepali" },
  "nso":    { endonym: "Sesotho sa Leboa",    english: "Northern Sotho" },
  "no":     { endonym: "Norsk",               english: "Norwegian" },
  "ny":     { endonym: "Chichewa",            english: "Nyanja" },
  "or":     { endonym: "ଓଡ଼ିଆ",                 english: "Odia" },
  "om":     { endonym: "Afaan Oromoo",        english: "Oromo" },
  "ps":     { endonym: "پښتو",                english: "Pashto" },
  "fa":     { endonym: "فارسی",               english: "Persian" },
  "pl":     { endonym: "Polski",              english: "Polish" },
  "pt-BR":  { endonym: "Português (Brasil)",  english: "Portuguese (Brazil)" },
  "pt-PT":  { endonym: "Português (Portugal)",english: "Portuguese (Portugal)" },
  "pa":     { endonym: "ਪੰਜਾਬੀ",                english: "Punjabi" },
  "qu":     { endonym: "Runa Simi",           english: "Quechua" },
  "ro":     { endonym: "Română",              english: "Romanian" },
  "ru":     { endonym: "Русский",             english: "Russian" },
  "sm":     { endonym: "Gagana Samoa",        english: "Samoan" },
  "sa":     { endonym: "संस्कृतम्",             english: "Sanskrit" },
  "gd":     { endonym: "Gàidhlig",            english: "Scottish Gaelic" },
  "sr":     { endonym: "Српски",              english: "Serbian" },
  "sn":     { endonym: "chiShona",            english: "Shona" },
  "sd":     { endonym: "سنڌي",                english: "Sindhi" },
  "si":     { endonym: "සිංහල",               english: "Sinhala" },
  "sk":     { endonym: "Slovenčina",          english: "Slovak" },
  "sl":     { endonym: "Slovenščina",         english: "Slovenian" },
  "so":     { endonym: "Soomaali",            english: "Somali" },
  "st":     { endonym: "Sesotho",             english: "Southern Sotho" },
  "es":     { endonym: "Español",             english: "Spanish" },
  "su":     { endonym: "Basa Sunda",          english: "Sundanese" },
  "sw":     { endonym: "Kiswahili",           english: "Swahili" },
  "sv":     { endonym: "Svenska",             english: "Swedish" },
  "tg":     { endonym: "Тоҷикӣ",              english: "Tajik" },
  "ta":     { endonym: "தமிழ்",                english: "Tamil" },
  "tt":     { endonym: "Татар",               english: "Tatar" },
  "te":     { endonym: "తెలుగు",              english: "Telugu" },
  "th":     { endonym: "ไทย",                 english: "Thai" },
  "ti":     { endonym: "ትግርኛ",                english: "Tigrinya" },
  "ts":     { endonym: "Xitsonga",            english: "Tsonga" },
  "tr":     { endonym: "Türkçe",              english: "Turkish" },
  "tk":     { endonym: "Türkmen",             english: "Turkmen" },
  "uk":     { endonym: "Українська",          english: "Ukrainian" },
  "ur":     { endonym: "اردو",                english: "Urdu" },
  "ug":     { endonym: "ئۇيغۇرچە",            english: "Uyghur" },
  "uz":     { endonym: "Oʻzbek",              english: "Uzbek" },
  "vi":     { endonym: "Tiếng Việt",          english: "Vietnamese" },
  "cy":     { endonym: "Cymraeg",             english: "Welsh" },
  "fy":     { endonym: "Frysk",               english: "Western Frisian" },
  "xh":     { endonym: "isiXhosa",            english: "Xhosa" },
  "yi":     { endonym: "ייִדיש",              english: "Yiddish" },
  "yo":     { endonym: "Yorùbá",              english: "Yoruba" },
  "zu":     { endonym: "isiZulu",             english: "Zulu" }
};

// Dual-context export: browser globals for popup.js, CJS for helper scripts.
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { LANGUAGES };
}
